/**
 * FRONTEND INTEGRATION GUIDE
 * 
 * This file contains the JavaScript functions you need to add to your existing frontend logic.
 * You asked not to create the frontend UI, but just how to add user input to the backend.
 * 
 * PREREQUISITES:
 * 1. The Python Backend must be running (python main.py).
 * 2. It will be hosted at http://localhost:8000 by default.
 */

// 1. Function to send User Data (for "Data Agent")
// Call this when the user submits their registration form.
async function submitUserData(formData) {
    // formData should be an object like:
    // {
    //   "name": "Amit Kumar",
    //   "age": 45,
    //   "income": 150000,
    //   "occupation": "Farmer",
    //   "state": "Uttar Pradesh",
    //   "disability": "No",
    //   "category": "Farmer"
    // }

    try {
        const response = await fetch("http://localhost:8000/api/store-user", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(formData)
        });

        const data = await response.json();
        console.log("Data Agent Response:", data);
        alert(data.message); // "User data saved securely."
        return true;
    } catch (error) {
        console.error("Error submitting user data:", error);
        alert("Failed to connect to backend.");
        return false;
    }
}

// 2. Function to get Recommendations (for "Analyzer Agent" + "Simplifier Agent")
// Call this when the user wants to see their eligible schemes.
// You can pass the same formData object.
async function getRecommendations(formData) {
    try {
        const response = await fetch("http://localhost:8000/api/recommend", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(formData)
        });

        const data = await response.json();
        console.log("Analyzer Agent Response:", data);

        // 'data.results' will contain the simplified explanations
        // Example usage:
        // displaySchemes(data.results);
        return data.results;

    } catch (error) {
        console.error("Error getting recommendations:", error);
        return [];
    }
}

// Example Helper: Displaying the simplified output
function displaySchemes(schemes) {
    const container = document.getElementById('results-container'); // Your UI container
    container.innerHTML = "";

    if (schemes.length === 0) {
        container.innerHTML = "<p>No specific matches found.</p>";
        return;
    }

    schemes.forEach(item => {
        // item.simple_explanation is the text generated by the Simplifier Agent
        const card = document.createElement('div');
        card.className = "scheme-card";
        card.innerHTML = `
            <h3>${item.title} (Match: ${Math.round(item.match_score * 100)}%)</h3>
            <div class="simple-text">
                ${item.simple_explanation.replace(/\n/g, '<br>')}
            </div>
            <hr>
        `;
        container.appendChild(card);
    });
}
